p1=int(input("Enter price of item 1: "))
p2=int(input("Enter price of item 2: "))
p3=int(input("Enter price of item 3: "))
print("Discount Details")
d1=int(input("Provide discount(in percentage) for the 1st server combo: "))
d2=int(input("Provide discount(in percentage) for the 2nd server combo: "))
d3=int(input("Provide discount(in percentage) for the 3rd server combo: "))
mob=input("Provide your 10 digit mobile number: ")
while(len(mob)!=10):
    mob=input("Wrong Input. Enter again: ")
print(" \n The resulting catalogue is: \n")
print(" Delhi Days \n R-Block, Model Town 3 \n Delhi:110009 \n")

print("Item                      Price")
print(" |                          |")
print("Item 1:                   ",p1)
print("Item 2:                   ",p2)
print("Item 3:                   ",p3)
print("Combo Pack 1:             ",(p1+p2)*(1-d1/100))
print("Combo Pack 2:             ",(p1+p3)*(1-d2/100))
print("Combo Pack 3:             ",(p2+p3)*(1-d3/100))
print("Super Saver:              ",(p1+p2+p3)*(1-28/100))
print("\nFor Home Delivery contact at: ",mob)
